import About from "@/components/about/about";
import MainSection from "@/components/main/main-section";
import path from "path";
import fs from "fs";
import {WorkExp} from "@/types/workExp";
import {Project} from "@/types/project";
import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next pages",
};// TODO look into metadata

export async function getStaticProps() {
    const projectFile = path.join(process.cwd(), "public/data/projects.json");
    const workFile = path.join(process.cwd(), "public/data/work-experience.json");
    return {
        props: {
            projects: JSON.parse(fs.readFileSync(projectFile, "utf8")),
            workExp: JSON.parse(fs.readFileSync(workFile, "utf8"))
        }
    };
}

export default function Bio({projects, workExp}: { projects: Project[], workExp: WorkExp[] }) {
    return <>
        {/* Hero */}
        <About/>

        {/* Main Section */}
        <MainSection projects={projects} workExp={workExp}/>
    </>;
}
